### ISSUE TITLE
For some reason the controller (Pocket Computer) doesn't work anymore

### ISSUE THREAD

**Issue by CyanKhaos** [JSH32/MineBoy#2]
It used to work but now it doesnt :c
I don't know what to add to things like that so i kinda have to do a ping pong conversation >.>
![image](https://github.com/JSH32/MineBoy/assets/110353639/a3f235d1-743f-45b2-a82b-6b2c51ff2723)

**Comment by KaidenChristman** [comment]
Im guessing its the computer ID. when I reached id 3 mine stopped working too.

**Comment by JSH32** [comment]
Did you guys ever manage a fix? I've never been able to figure out how to cause his intentionally, got IDs going all the way to 20

**Comment by KaidenChristman** [comment]
I personally think it may be cc version. If Mythic could say if their running forge or fabric I might have an idea because I’m experiencing this issue in the fabric version of the mod but idk about forge.

**Comment by JSH32** [comment]
I'm using the newest build of CC with Fabric

**Comment by JSH32** [comment]
Just noticed in your screenshot that the wireless modem isn't lighting up like it should be for rednet. Are you sure that you're specifying the correct ID?

**Comment by JSH32** [comment]
Sorry for the late reply but I think I just figured it out. I think you may be specifying "back" as your modem (it isn't the modem) instead of the actual modem ID in the `mineboy_config.lua`, back could be 4 devices and also the block is lighting up (forgot the name of it). I'm closing this now since I'm also probably assuming this isn't even relevant anymore LMAO
