### ISSUE TITLE
allow GBA

### ISSUE THREAD

**Issue by KaidenChristman** [JSH32/MineBoy#3]
please im begging

**Comment by JSH32** [comment]
I was thinking about it but GBA has a multiple much larger palettes. This means huge quantization will make it impractical, with GBC the amount of colors is a lot less. Also increased screen dimensions will be difficult, as well as requiring either costly compression when sending frames or changing the request size limit in ComputerCraft settings.

I'm leaving this open since I'm still somewhat considering it as a proof of concept but don't get your hopes up

**Comment by KaidenChristman** [comment]
also im running into an issue with line 53 of the mineboy.lua, it can't seem to find the monitor attached to the pc

**Comment by JSH32** [comment]
Is the monitor (and wired modems) connected? How are you specifying the monitor ID? Try through the direct ID instead of directions. I'm closing the issue but you can still comment

**Comment by KaidenChristman** [comment]
Everything is connected properly and setup as intended. I may be able to provide video if needed.

**Comment by KaidenChristman** [comment]
Commented on wrong issue lol. Found error and fixed, I just forgot to turn on modems
